FROM garyzhang1982001/httpproxy:latest



ENV PROXY_PORT=9999
ENV PROXY_HOST=0.0.0.0

#RUN echo "aaa" > /app/output.txt

EXPOSE 9999



# Run proxy.py when the container launches
# Use 0.0.0.0 as host to allow connections from outside the container
#CMD ["uvicorn", "proxy_server:app"] 
USER 10014
CMD ["python", "proxy_server.py"] 
